### ISSUE TITLE
Probem with utf8

### ISSUE THREAD

**Issue by akvalibra** [FrancisFaure/vfp_tmlanguage_generator#1]
Problem with utf8. Wrong conversion. 
The default code page in my Windows 10 is Cyrillic 1251 (Macedonian)

This is the correction. 

function utf8(m.lsString as string) as string
  return strconv(m.lsString,9)
  _!_ return strconv(strconv(m.lsString, 1),9)
endfunc

![image](https://cloud.githubusercontent.com/assets/8169630/15528667/41d2e2ae-2246-11e6-8f20-806928b6918f.png)

**Comment by FrancisFaure** [comment]
Hi akvalibra,
- I just push a commit with your update : could you check it ?

About your .PRG in VSCode have you found a workaround for encoding .PRG Files in your 1251 PageCode ?

Best regards
Francis
