### ISSUE TITLE
The VSCode doesn't open as expected 

### ISSUE THREAD

**Issue by fabio-filho** [FrancisFaure/vfp_tmlanguage_generator#2]
I've made the installation step by step, but the VSCode isn't opening with the .prg file.

**Comment by FrancisFaure** [comment]
Hi Fabio, 
What version of VSCode are you using?
And what is your operating system?
with best regards
Francis

**Comment by fabio-filho** [comment]
Hello Francis,
That was my fault, I and my friend have put it to work  ...
Thanks !!
